// Import all Fluent API definitions
import './roles/scrum-poker-roles.now.ts'
import './tables/poker-session.now.ts'
import './tables/session-participant.now.ts'
import './tables/poker-vote.now.ts'
import './acls/poker-session-acls.now.ts'
import './acls/session-participant-acls.now.ts'
import './acls/poker-vote-acls.now.ts'
import './business-rules/session-state-change.now.ts'
import './script-includes/scrum-poker-ajax.now.ts'
import './scripted-rest-apis/scrum-poker-api.now.ts'
import './ui-pages/scrum-master.now.ts'
import './ui-pages/scrum-user.now.ts'
import './ui-pages/scrum-master-websocket.now.ts'
import './ui-pages/scrum-user-websocket.now.ts'